[sys.base]
dependency = [
    "zsh",
    "curl",
    "ncdu",
    "git",
    "iproute2",
    "python3-pip",
    "ripgrep",
    "tmux",
]

[sys.enhanced]
dependency = [
    "httpie",
    "exa",
    "neovim",
    "bat",
    "btop",
    "net-tools",
    "fd",
    "fzf",
    "ranger",
    "tree",
]

[sys.optional]
dependency = ["gnupg", "jq", "pass", "pwgen", "rsync", "shellcheck", "unzip"]


[python]
dependency = ["euporie"]

[python.jupyter]
dependency = [
    "jupyter",
    "jupyterlab",
    "jupyterlab_code_formatter",
    "black",
    "isort",
    "nb_conda_kernels",
    "jupyterlab-lsp",
    "python-lsp-server",
]
