[sys]
dependency = [
    "zsh", 
    "curl", 
    "ncdu", 
    "git", 
    "iproute2", 
    "python3-pip",
    "ripgrep", 
    "tmux"
]

[sys.python]
dependency = [
    "euporie"
]

[sys.python.jupyter]
dependency = [
    "jupyter", 
    "jupyterlab", 
    "jupyterlab_code_formatter", 
    "black" , 
    "isort", 
    "nb_conda_kernels", 
    "jupyterlab-lsp", 
    "python-lsp-server", 
]